### ISSUE TITLE
Migrate images to gcr.io repo and enable automatic builds

### ISSUE THREAD

**Issue by davidjumani** [kubernetes-sigs/cluster-api-provider-cloudstack#109]
As part of the integration with the broader Kubernetes community, all CAPI images are hosted on the GCR repo.
I've created an issue [here](https://github.com/kubernetes/k8s.io/pull/3792) requesting a new repo for CAPC
Once done we can modify the image to point to the GCR repo

Also once done, can look into enabling automatic builds https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/README.md

**Comment by rohityadavcloud** [comment]
Could be closed now @davidjumani ?

**Comment by davidjumani** [comment]
The repo has been created so the first part is complete
Created a PR for the second in https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/136

**Comment by davidjumani** [comment]
This has been added in https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/160 && https://github.com/kubernetes/test-infra/pull/27418
