### ISSUE TITLE
Inconsistent JSON tags

### ISSUE THREAD

**Issue by davidjumani** [kubernetes-sigs/cluster-api-provider-cloudstack#113]
In certain structs, the JSON tags case is not consistent. 
Eg: `CloudStackMachineSpec.AffinityGroupIDs` is tagged to `affinitygroupids` while `CloudStackMachineSpec.ZoneID` is tagged to `zoneID`. 

There are others and it would be great to standardise the tags to a certain convention prior to an initial release so that down the line there won't be any compatibility issues

**Comment by rejoshed** [comment]
Please see linked PR. I only found a few JSON tags that I could tell needed changing.

Hopefully we can close this issue with said PR.
