### ISSUE TITLE
Possibility to add a secondary NIC to machines

### ISSUE THREAD

**Issue by vdombrovski** [kubernetes-sigs/cluster-api-provider-cloudstack#161]
/kind feature

**Describe the solution you'd like**
Currently, it's not quite possible to force a CAPC infrastructure that creates machines with multiple network interfaces; the only network related parameter is the following:

```
export CLOUDSTACK_NETWORK_NAME=XYZ
```

Sometimes however it's useful to create an infrastructure that will be connected to multiple networks (e.g. a storage network for a custom CSI, or for implementing LoadBalancers)

It would be nice to be able to add another network (that exists inside Cloudstack) to all machines created as part of CAPC network.

**Anything else you would like to add:**
N/A

**Environment:**

- Cluster-api-provider-cloudstack version: 0.4.4
- Kubernetes version: (use `kubectl version`): v1.23.3
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04 LTS

**Comment by davidjumani** [comment]
Thanks for the idea @vdombrovski 
We will add it to the list and look into it

**Comment by bragonznx** [comment]
to follow :+1:
