### ISSUE TITLE
CloudStackMachine could not be deleted when using invalid serviceOffing

### ISSUE THREAD

**Issue by wanyufe** [kubernetes-sigs/cluster-api-provider-cloudstack#202]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
E2E testing detects a bug that when invalid serviceOffering is configured to create CloudStackMachine. This CloudStackMachine could not be deleted due to missing instanceID. 

**What did you expect to happen:**
CloudStackMachine should be deleted successfully without stopping cluster deletion.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
This is for admin doc purpose, a PR had been created to address this:https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/201

**Environment:**

- Cluster-api-provider-cloudstack version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by hrak** [comment]
This issue seems to be addressed by #201 already. Does it need to stay open?
