### ISSUE TITLE
CAPC does not resolve service offering with zone as additional filtering parameter

### ISSUE THREAD

**Issue by chrsmeca** [kubernetes-sigs/cluster-api-provider-cloudstack#207]
/kind bug

**What steps did you take and what happened:**
The following error is generated when multiple cloud stack zones with the same offering name exist.

E0104 21:43:15.451029       1 controller.go:317] controller/cloudstackmachine "msg"="Reconciler error" "error"="1 error occurred:\n\t* expected 1 Service Offering with name 4 vCPU 8 GiB RAM, but got 2\n\n" "name"="<<redacted>>" "namespace"="<<redacted>>" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="CloudStackMachine" 

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-cloudstack version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by wanyufe** [comment]
PR https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/208 fixed the issue.
