### ISSUE TITLE
Merge the AWS build container into the project

### ISSUE THREAD

**Issue by chrisdoherty4** [kubernetes-sigs/cluster-api-provider-cloudstack#228]
The CI is failing on PRs often because the Go version is outdated in the build container. When AWS donated CAPC to the CNCF the build container sources we're left behind. This ticket is to track their migration.

[Failing CI example](https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/224)
[CI jobs referencing build image](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api-provider-cloudstack/capi-provider-cloudstack-presumbit.yaml#L68)

/kind feature
/assign chrisdoherty4

**Comment by g-gaston** [comment]
@chrisdoherty4 now that we use the community maintained image, this is done right?

**Comment by chrisdoherty4** [comment]
Correct, we don't need this.
