### ISSUE TITLE
Support scale from zero  ( cluster-autoscaler )

### ISSUE THREAD

**Issue by lukasmrtvy** [kubernetes-sigs/cluster-api-provider-cloudstack#229]
/kind feature
Support scale from zero https://github.com/kubernetes/autoscaler/pull/4840

**Comment by ozhankaraman** [comment]
do we have any news on this issue?

**Comment by lukasmrtvy** [comment]
@ozhankaraman Can You try to set capacity annotations https://cluster-api.sigs.k8s.io/tasks/automated-machine-management/autoscaling#scale-from-zero-support ( it is working in CAPO ) ?

**Comment by ozhankaraman** [comment]
it works with below annotations on capc but because memory and cpu definitions there it stays on minimum 1 node, never goes to 0. If you remove capacity.cluster-autoscaler.kubernetes.io/memory and capacity.cluster-autoscaler.kubernetes.io/cpu there CAS will not scale up from zero.
```
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "0"
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "10"
    capacity.cluster-autoscaler.kubernetes.io/memory: "8G"
    capacity.cluster-autoscaler.kubernetes.io/cpu: "4"
```

**Comment by g-gaston** [comment]
Moving to v0.5.0 since this is a new feature and we are only prioritizing vital bugfixes for v0.4.9
