### ISSUE TITLE
Additional ObjectMeta field should be removed from CloudStackMachineTemplate

### ISSUE THREAD

**Issue by vignesh-goutham** [kubernetes-sigs/cluster-api-provider-cloudstack#237]
`CloudStackMachineTemplate` API for `v1beta2` has an additional `ObjectMeta` in one of its children structs (`CloudStackMachineTemplateResource`. This field is not required and is not used anywhere. While this is predominately non-intrusive, kube-apiserver from 1.25 enabled `ServerSideValidation` as the feature matured to beta. When unmarshalling a struct from this API, in includes `creationtimestamp` as nil as part of that additional ObjectMeta field. A yaml generated from un-marshalling struct fails server side validation.

API field to be removed - https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/blob/8c69f07f748b2785da403216e5e0b9c0cb1fccdb/api/v1beta2/cloudstackmachinetemplate_types.go#L28

**Comment by hrak** [comment]
@rohityadavcloud i guess this can be closed since the linked PR is merged
