### ISSUE TITLE
Remove Affinity Group dependency on owner ref

### ISSUE THREAD

**Issue by vignesh-goutham** [kubernetes-sigs/cluster-api-provider-cloudstack#240]
/kind bug

Cloudstack machine spec accepts affinity group in two ways.
1. Managed way where we can just say `pro` or `anti` and CAPC will create an affinity group accordingly for each node group. Ex. for KCP, Etcd, and each worker node group.
2. Provide an already created list of affinity group IDs

In the managed way, CAPC gets the owner ref of CAPI machine and uses the owner name to identify and generate a unique name per node group. While this would work in most situations, owner ref of CAPI machines is not a solid or strict API spec to identify the node role or node group. For instance, ETCD machines can be owned by etcdamd controller, but when the controller chooses to delete old machines, it simply removes its ownership, at which point, CAPI cluster owns those old etcd machines. 

An intermediary API that is responsible to track node roles along with affinity or anti-affinity status should be established from which affinity group names should be generated. This API should derive the affinity details during KCP/Cluster creation time.

**Comment by rohityadavcloud** [comment]
Fixed by https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/286 cc @vignesh-goutham pl review and test, thanks.
