### ISSUE TITLE
Upgrade to CAPI v1.3

### ISSUE THREAD

**Issue by chrisdoherty4** [kubernetes-sigs/cluster-api-provider-cloudstack#248]
## Summary

CAPC v0.4 uses CAPI v1.2. To provide users with at least 1 CAPC release using CAPI 1.3, I'm proposing we do a v0.5 release that uses CAPI 1.3 before upgrading to CAPI 1.4.

/kind feature

**Comment by weizhouapache** [comment]
@chrisdoherty4 
Imho, we can skip CAPI 1.3 and upgrade to CAPI 1.4 in 0.5.0 release.

**Comment by chrisdoherty4** [comment]
I was giving thought to users who want to upgrade CAPC but are using CAPI 1.3. Going through the motions of 1.3 then 1.4 would give them an upgrade path.

Are you saying we shouldn't worry?

**Comment by chrisdoherty4** [comment]
I took a look at the changes between CAPI versions and what we're using in CAPC and I think upgrading straight to 1.4 is OK.

**Comment by weizhouapache** [comment]
@chrisdoherty4 
thanks for the checking

I used CAPC v0.4.8 with various clusterctl versions (1.2,1.3,1.4) without any issue
I also noticed aws eks use capi 1.3 and capc 0.4.8-rc1
https://github.com/aws/eks-anywhere/blob/main/go.mod#L62

it may be not required to use the same capi version in capc.
we could test the compatilibity when capc v0.5.0 is released.
