### ISSUE TITLE
Upgrade Go to 1.20

### ISSUE THREAD

**Issue by vignesh-goutham** [kubernetes-sigs/cluster-api-provider-cloudstack#253]
/kind feature

Upgrade Go to 1.20.x

**Comment by hrak** [comment]
Its probably best to stick with the Go version that the k8s dependencies use. CAPC currently depends on Kubernetes 1.25 which uses Go 1.19. Go 1.20 is only used starting from Kubernetes 1.27.

**Comment by vignesh-goutham** [comment]
I like that, lets migrate to 1.20 Golang when we start supporting 1.27. I'll create separate issues for supporting more kubernetes versions.

**Comment by hrak** [comment]
Looks like we can move to 1.20 now that Kubernetes has done so for older k8s versions: [Bump builders to use Go 1.20.5 for branches 1.26/1.25/1.24](https://github.com/kubernetes/release/pull/3145)
