### ISSUE TITLE
"post-cluster-api-provider-cloudstack-push-images" job failed for 201 days

### ISSUE THREAD

**Issue by weizhouapache** [kubernetes-sigs/cluster-api-provider-cloudstack#266]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

https://github.com/kubernetes-sigs/cluster-api/issues/8784

The log of latest run
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-cluster-api-provider-cloudstack-push-images/1664572298696331264

**What did you expect to happen:**

succeed.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

It is because the docker container does not have gcc installed.

**Environment:**

- Cluster-api-provider-cloudstack version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by g-gaston** [comment]
@weizhouapache any clue what part of the code is using cgo?
