### ISSUE TITLE
Reconcile a CAPC cluster to a CKS cluster

### ISSUE THREAD

**Issue by rohityadavcloud** [kubernetes-sigs/cluster-api-provider-cloudstack#310]
/kind feature

**Describe the solution you'd like**

CAPC reconciles various resources in CloudStack, we want to see CAPC leverage and reconcile notion of a CAPC k8s cluster to a CKS (unmanaged) cluster.

The CKS cluster resource in CloudStack captures notion of a k8s cluster in CloudStack, and recently a feature improvement made it possible to have notion of unmanaged k8s cluster with https://github.com/apache/cloudstack/pull/7515 with documentation at https://github.com/apache/cloudstack-documentation/pull/315 and API support via go-sdk change https://github.com/apache/cloudstack-go/pull/59. A PR proposed https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/250 which couldn't satisfy review from other stakeholders. With this issue, alternative options and approaches can be discussed or the previous PR reimagined.

As a CAPC user I would want the following:

- Ability to see my CAPC cluster show up as unmanaged CKS cluster in CloudStack (API and UI)
- Be able to see usage, of my CAPC cluster via CKS cluster (cpu, memory etc.)
- As MachineSets are added/removed, the related instances can be added removed in CKS 'unmanaged' cluster
- In large environment, esp a typical CI/CD use-cases, if as a user I lose/forget my CAPC admin cluster I should be able to manually delete the CAPC cluster resources (namely, VMs and networks)
- I should be able to do this as a user account type (note: a CloudStack role has a list of allowed/disallowed APIs, however, an account type control ability of an account type to do certain things such as acquire public IP of choice in a given shared/isolated/vpc network etc. needed typically for CAPC cluster)
- Prefer not to use another tool, than CAPC for reconciliation of a CAPC cluster to a CloudStack Kubernetes Service (CKS) cluster

Brief design doc: (to be expanded by @vishesh92)

**Comment by chrisdoherty4** [comment]
Lots of relevant conversation has already taken place on https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/250.

**Comment by g-gaston** [comment]
Moving to v0.5.0 since this is a new feature (and requires some more discussion if I recall correctly) and we are only prioritizing vital bugfixes for v0.4.9

**Comment by rohityadavcloud** [comment]
@weizhouapache @vishesh92 and I want to revisit this for v0.5.0, by making the integration/reconciliation disabled by default that we may revisit to enable by default in future. Users who want this feature will have to enable it; the related feature is already made into ACS 4.19 now (under RC1/testing/voting now): https://github.com/apache/cloudstack/pull/7515 and https://github.com/apache/cloudstack-documentation/pull/315

We've gathered a lot of support in the CloudStack community esp. during last year's meet-ups and CloudStack Collaboration conference, where users want to use the CKS feature with CAPC as high-level API/UI abstraction for their Kubernetes clusters; having CAPC clusters show us as unmanaged CKS cluster serves a lot of their requirements, with path of having CAPC cluster being orchestrated via CloudStack opening up in future.

**Comment by g-gaston** [comment]
> @weizhouapache @vishesh92 and I want to revisit this for v0.5.0, by making the integration/reconciliation disabled by default that we may revisit to enable by default in future. Users who want this feature will have to enable it; the related feature is already made into ACS 4.19 now (under RC1/testing/voting now): [apache/cloudstack#7515](https://github.com/apache/cloudstack/pull/7515) and [apache/cloudstack-documentation#315](https://github.com/apache/cloudstack-documentation/pull/315)
> 
> We've gathered a lot of support in the CloudStack community esp. during last year's meet-ups and CloudStack Collaboration conference, where users want to use the CKS feature with CAPC as high-level API/UI abstraction for their Kubernetes clusters; having CAPC clusters show us as unmanaged CKS cluster serves a lot of their requirements, with path of having CAPC cluster being orchestrated via CloudStack opening up in future.

That sounds good to me! Thanks y'all for doing all the user research!

To facilitate future reviews, could y'all add this info (opt-in feature) to the issue description?

I would also love to discuss first the high level implementation first (here in the issue is totally fine although if y'all want to write a one pager design doc that's great too), just to avoid churn during PR reviews.
