### ISSUE TITLE
Template for v1.27 is broken

### ISSUE THREAD

**Issue by vdombrovski** [kubernetes-sigs/cluster-api-provider-cloudstack#325]
/kind bug

**What steps did you take and what happened:**

Tried deploying using the 1.27 template.

Le control plane init was stuck on fetching the following image and would not reconcile:

```k8s.gcr.io/coredns:v1.10.1```

Further analysis releals that coredns image has been moved to 

```k8s.gcr.io/coredns/coredns:v1.10.1```

See: https://console.cloud.google.com/gcr/images/k8s-artifacts-prod/eu/coredns/coredns

**What did you expect to happen:**

Deployment succeeds

**Environment:**

- Cluster-api-provider-cloudstack version:  0.4.8
- Kubernetes version: (use `kubectl version`):  1.27
- OS (e.g. from `/etc/os-release`):

**Comment by rohityadavcloud** [comment]
is this still an issue @vdombrovski ? cc @g-gaston @hrak @shwstppr

**Comment by vdombrovski** [comment]
Hello @rohityadavcloud, my last comment was incorrect, here is the actual input:

![2024-02-28_11-14](https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/assets/19999157/14bb7089-115e-4b45-a1de-f68db2889aad)

As a matter of fact, gcr.k8s.io is deprecated. The correct repo to be used is now: registry.k8s.io

Example: registry.k8s.io/kube-apiserver:v1.27.8

**Comment by rohityadavcloud** [comment]
cc @weizhouapache @vishesh92 @kiranchavala

**Comment by weizhouapache** [comment]
just checked the build log, it did use registry.k8s.io.

need some investigation

![image](https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/assets/57355700/4965f8d2-90df-4e02-b8e7-08211338d575)

**Comment by vdombrovski** [comment]
@weizhouapache I think the image is not up to date or something

```
curl -sI http://packages.shapeblue.com/cluster-api-provider-cloudstack/images/kvm/ubuntu-2004-kube-v1.27.2-kvm.qcow2.bz2 | grep "Last"

Last-Modified: Thu, 12 Oct 2023 09:39:49 GMT
```

Says here "Last Modified 12 Oct 2023". Is there another image version maybe?

**Comment by weizhouapache** [comment]
> @weizhouapache I think the image is not up to date or something
> 
> ```
> curl -sI http://packages.shapeblue.com/cluster-api-provider-cloudstack/images/kvm/ubuntu-2004-kube-v1.27.2-kvm.qcow2.bz2 | grep "Last"
> 
> Last-Modified: Thu, 12 Oct 2023 09:39:49 GMT
> ```
> 
> Says here "Last Modified 12 Oct 2023". Is there another image version maybe?

@vdombrovski 
actually the image was built in July 2023 (the log above is copied from the build job on jenkins)

**Comment by vdombrovski** [comment]
Hello @weizhouapache, okay but it doesn't really work (nor did the image from the time this issue was created). Is there something I'm missing here? Is there another image that includes the fix that we can test?

**Comment by weizhouapache** [comment]
> Hello @weizhouapache, okay but it doesn't really work (nor did the image from the time this issue was created). Is there something I'm missing here? Is there another image that includes the fix that we can test?

@vdombrovski 
that's a bit strange

it works fine in my testing
sha512sum of the template is  "e6a7d37d8b8c368bee63d6977f37328cbd6a2cc936a56ff55051fb9e9572053aca10807ebeb81e55e4eb2163d5a895c40e616e52a9d016af807661cb594998fe"

**Comment by vdombrovski** [comment]
@weizhouapache what version of the CAPC provider are you using? 0.5.0 or 0.4.8?

**Comment by weizhouapache** [comment]
@vdombrovski 
I did a quick testing again, the cluster looks ok at first glance, but nodes are not ready

![image](https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/assets/57355700/ebc1b3de-e44a-4820-ac42-3c9a67cdbe7d)

**Comment by weizhouapache** [comment]
@vdombrovski 
have you tested other images ?

**Comment by vdombrovski** [comment]
We are using the 1.23.3 image, it launches successfully. 

This morning, I went through the 0.4.9 release notes, and saw this:

https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/224

The issue is not in the template, but in the infrastructure components. We are upgrading our instance to 0.4.9 as we speak, I will test the 1.27 template once again; pretty sure this is what is causing the issue here.

**Comment by weizhouapache** [comment]
> We are using the 1.23.3 image, it launches successfully.
> 
> This morning, I went through the 0.4.9 release notes, and saw this:
> 
> #224
> 
> The issue is not in the template, but in the infrastructure components. We are upgrading our instance to 0.4.9 as we speak, I will test the 1.27 template once again; pretty sure this is what is causing the issue here.

I agree with you.

I faced a similar issue last year in e2e test, you may refer to https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/243

**Comment by vdombrovski** [comment]
Thank you @weizhouapache, using the provided e2e tests I finally managed to figure out what was wrong with this. The issue was definitely on our side; not sure how we didn't notice it before. For posterity, here is a quick explanation:

The repository configuration is in KubeadmControlPlane:
```
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: mycluster-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      imageRepository: registry.k8s.io # This line
```

After you do a clusterctl generate, make sure that are using the correct repo: registry.k8s.io. Set it before applying if it's not the case. Afaik:

- Before 0.4.9: you need to set the correct imageRepository: registry.k8s.io
- 0.4.9: the default value is now registry.k8s.io, so no need to do anything.

Closing this issue, again, thank you for your help
