### ISSUE TITLE
Affinity group deletion gets stuck with CloudStack API errors

### ISSUE THREAD

**Issue by vignesh-goutham** [kubernetes-sigs/cluster-api-provider-cloudstack#339]
/kind bug

**Describe the solution you'd like**

When deleting affinity group, the controller issues a delete API for affinity group which can fail due to reasons including
- Networking issues like flaky network
- Cloudstack management server issues

These issues can cause the API to return an error but can proceed and deletes the affinity group on CloudStack. In the subsequent reconcile loops, the controller does not find the affinity group on CloudStack and doesn't remove the finalizer. This results in affinity group resource to be stuck in deletion.

**Comment by rohityadavcloud** [comment]
Closing as #340 is merged
