### ISSUE TITLE
Native LB support ? 

### ISSUE THREAD

**Issue by lukasmrtvy** [kubernetes-sigs/cluster-api-provider-cloudstack#68]
Hey 👋 Is there any chance to implement support for a native Cloudstack Load Balancer instead of kube-vip ?

See:
https://github.com/apache/cloudstack-kubernetes-provider

Thanks

**Comment by pmotyka** [comment]
Thanks for the inquiry, @lukasmrtvy.  We'll follow up shortly with thoughts on supporting the native CloudStack Load Balancer as an alternative to kube-vip.

**Comment by davidjumani** [comment]
@lukasmrtvy Could you elaborate a bit more on the requirement and use case ?

As of now, if the CAPC cluster is on an isolated network, it automatically acquires the Public IP, and creates the required firewall and load balancer (handled by CloudStack's own VR) rules to balance traffic across all control plane nodes.

In case any service needs to be exposed outside of CloudStack, https://github.com/apache/cloudstack-kubernetes-provider can be deployed along with the corresponding Service and LoadBalancer configured on the cluster. The CloudStack Kubernetes Provider will work as usual, creating a new public IP and load balancing traffic for the service
